name: Terraform Plan

on:
  push:
    branches: [ main ]
    paths:
      - 'infra/**'
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read
  pull-requests: write

env:
  TF_WORKING_DIR: infra

jobs:
  plan:
    runs-on: ubuntu-latest

   
    outputs:
      plan_status: ${{ steps.plan_step.outputs.plan_status }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::381492201204:role/GitHubActionsOIDCRole
          aws-region: us-east-1

      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init -input=false

      - name: Terraform Plan
        id: plan_step
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          terraform plan -input=false -out=tfplan.binary
          echo "plan_status=success" >> $GITHUB_OUTPUT

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform apply -input=false -auto-approve tfplan.binary
