name: Terraform Destroy

on:
  workflow_dispatch:   # Manual trigger only

env:
  TF_WORKING_DIR: infra

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  destroy:
    runs-on: ubuntu-latest

    # Enable approval
    environment: production

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: DEBUG OIDC TOKEN
        uses: actions/github-script@v7
        with:
          script: |
            const token = await core.getIDToken('sts.amazonaws.com');
            const payload = token.split('.')[1];
            const claims = JSON.parse(Buffer.from(payload, 'base64').toString());
            console.log("===== OIDC CLAIMS =====");
            console.log(JSON.stringify(claims, null, 2));
            console.log("========================");

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::605731693050:role/GitHubActionsOIDCRole
          aws-region: us-east-1

      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init -input=false

      - name: Terraform Destroy
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform destroy -input=false -auto-approve
