name: Deploy VPC Module

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Print public IP of GitHub runner
        run: |
          echo "Runner public IP:"
          curl -s https://checkip.amazonaws.com

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var-file="terraform.tfvars"

      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file="terraform.tfvars"
